version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0
  win: circleci/windows@4.1.1

jobs:
  deploy:
    executor: win/default
    steps:
      - checkout

      #download & cashe the dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #run tests
      - run:
          name: Run Tests
          command: npm run test

      - run:
          name: build
          command: npm run build

      - run:
          name: deploy
          command: npm run deploy

workflows:
  deploy_wf:
    jobs:
      #- node/test:
          #version: "15.1"
          #post-steps:
            #- run: npm run build
            #- aws-s3/copy:
                #from: dist/
                #to: s3://sample-app-vue
                #arguments: --recursive
      - deploy
