version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0
  aws-cli: circleci/aws-cli@1.0
  eb: circleci/aws-elastic-beanstalk@1.0
  angular: okode/angular@2.0.13

commands:
  install_client:
    description: "Client Installation"
    # to cashe the requried files like node_modules instead of running npm install each time for the client project
    steps:
      - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run:
            name: Install Client Dependencies
            command: npm run client:install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  install_server:
    description: "Server Installation"
    # to cashe the requried files like node_modules instead of running npm install each time for the server project
    steps:
      - restore_cache:
            keys:
              - v2-dependencies-{{ checksum "package.json" }}
              - v2-dependencies-
      - run:
            name: Install Server Dependencies
            command: npm run server:install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

jobs:
  # to build both the client & server projects
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - node/install-npm
      - checkout
      - install_client
      - install_server
      - run:
          name: Build Client
          command: npm run client:build
      - run:
          name: Build Server
          command: npm run server:build
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-npm
      - checkout
      - install_client
      - install_server
      - run:
          name: Test Client
          command: npm run client:test
      - run:
          name: Test Server
          command: npm run server:test
  deploy:
    # to deploy both the front & backend projects
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - node/install-npm
      - aws-cli/setup
      - eb/setup
      - checkout
      - install_client
      - install_server
      - run:
          name: Deploy Client
          command: npm run client:deploy
      - run:
          name: Deploy Server
          command: npm run server:deploy

workflows:
  deploy:
    jobs:
      - build
        filters:
          branches:
            only: [master]
      - test
        requires:
          - build
      - deploy
        requires:
          - test
